### ISSUE TITLE
Slack Access Log: "pull table slack_access_log error: paid only"

### ISSUE THREAD

**Issue by CrestLee** [selefra/selefra-provider-slack#3]

**Comment by monserrat101** [comment]
When did this log occur? Can I help you?

**Comment by monserrat101** [comment]
Tomorrow the boss will give you a high-privilege token for test

**Comment by monserrat101** [comment]
The token permission given by the boss is still not enough. First, we skip the access_log table and release v0.0.1, so that the cloud can interconnect with it. After the token permission is added, we test access_log and add a v0.0.2  @leonynn
